# Makefile para mlab0-ex01-fibonacci.c

CC = gcc
CFLAGS = -Wall -pthread

TARGET = mlab0-ex02-busca_binaria
SRC = mlab0-ex02-busca_binaria.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
